export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const PLANET_REQUEST = 'PLANET_REQUEST';
export const PLANET_SUCCESS = 'PLANET_SUCCESS';
export const PLANET_FAILURE = 'PLANET_FAILURE';

export const LOGOUT = 'LOGOUT';